spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/whole_mylife_db?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 12345678
  mail:
    host: smtp.163.com
    username: z18332330319@163.com
    password: BLUQLTWDFASZEEEZ
    port: 465
    properties:
      from: z18332330319@163.com
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  data:
    redis:
      database: 0
      host: localhost
      port: 6379